Repository TEAM-PLAYTOGETHER/PlayTogether_Server, pull requests merged in 2022-08, with the labels that each got.

#130 [FIX] 번개 리스트 GUI 수정에 따른 데이터 변경
  src/db/lightDao.js
  src/service/lightService.js
Labels: 🐞 버그, light, 🐱제준

#131 번개 리스트 데이터 수정 배포
  src/db/lightDao.js
  src/service/lightService.js
Labels: 🐞 버그, light, 🐱제준, 🚀 릴리즈

#132 hotfix: 번개 상세 보기 페이지네이션 제거
  src/db/lightDao.js
  src/service/lightService.js
Labels: 🐞 버그, light, 🐱제준, 🚀 릴리즈

#135 fix: 번개 마감 여부 추가
  src/service/lightService.js
Labels: 🚀 릴리즈

#114 Refactor: 로그인 시 refresh token 추가
  src/constants/responseMessage.js
  src/controller/authController.js
  src/index.js
  src/lib/jwtHandler.js
  src/lib/jwtUtil.js
  src/lib/redis.js
  src/middlewares/jwtAuthorization.js
  src/package-lock.json
  src/package.json
  src/routes/authApi.js
  src/service/authService.js
Labels: 🛠 리팩터링, user, 👾승헌

#134 Feat: 멀티 프로필 등록
  src/constants/responseMessage.js
  src/controller/userController.js
  src/db/crewUserDao.js
  src/lib/nicknameVerify.js
  src/routes/userAPi.js
  src/service/crewService.js
Labels: ⚡️ 기능, user, 👾승헌

#128 Feat: 소셜로그인 API 구현
  src/db/authDao.js
  src/db/userDao.js
  src/index.js
  src/package-lock.json
  src/package.json
  src/passport/googleStrategy.js
  src/passport/index.js
  src/passport/kakaoStrategy.js
  src/routes/authApi.js
  src/service/authService.js
  src/service/userService.js
Labels: ⚡️ 기능, user, 👾승헌

#138 [feat] 상대방 id값을 통해 채팅방 번호를 가져오는 API 추가
  src/constants/responseMessage.js
  src/controller/messageController.js
  src/routes/messageAPI.js
  src/service/messageService.js
Labels: ⚡️ 기능, 🧐 동근, message

#140 [release] 이미지 null 버그 수정, 채팅방 확인 API 추가, refreshToken 추가
  src/constants/responseMessage.js
  src/controller/authController.js
  src/controller/lightController.js
  src/controller/messageController.js
  src/controller/userController.js
  src/db/authDao.js
  src/db/crewUserDao.js
  src/db/lightDao.js
  src/db/userDao.js
  src/index.js
  src/lib/jwtHandler.js
  src/lib/jwtUtil.js
  src/lib/nicknameVerify.js
  src/lib/redis.js
  src/middlewares/imageUpload.js
  src/middlewares/jwtAuthorization.js
  src/middlewares/multer.js
  src/package-lock.json
  src/package.json
  src/passport/googleStrategy.js
  src/passport/index.js
  src/passport/kakaoStrategy.js
  src/routes/authApi.js
  src/routes/lightApi.js
  src/routes/messageAPI.js
  src/routes/userAPi.js
  src/service/authService.js
  src/service/crewService.js
  src/service/lightService.js
  src/service/messageService.js
  src/service/userService.js
Labels: 🚀 릴리즈

#142 Feat: 동아리 프로필 유저 닉네임 중복 확인
  src/controller/userController.js
  src/db/userDao.js
  src/routes/userAPi.js
  src/service/userService.js
Labels: ⚡️ 기능, user, 👾승헌

#143 닉네임 중복확인 추가
  src/controller/userController.js
  src/db/userDao.js
  src/routes/userAPi.js
  src/service/userService.js
Labels: ⚡️ 기능, user, 👾승헌

#145 [refactor] 소켓서버와 기존 API 서버 연결
  src/app.js
  src/db/userDao.js
  src/index.js
  src/lib/redis.js
  src/package-lock.json
  src/package.json
  src/socket.js
Labels: 🛠 리팩터링, 🧐 동근, message

#147 [refactor] 슬랙봇 추가를 위한 예외처리 구조 수정
  src/app.js
  src/controller/authController.js
  src/controller/crewController.js
  src/controller/lightController.js
  src/controller/messageController.js
  src/controller/scrapController.js
  src/controller/userController.js
  src/db/authDao.js
  src/db/crewDao.js
  src/db/crewUserDao.js
  src/db/lightDao.js
  src/db/lightUserDao.js
  src/db/messageDao.js
  src/db/scrapDao.js
  src/db/userDao.js
  src/service/authService.js
  src/service/crewService.js
  src/service/lightService.js
  src/service/messageService.js
  src/service/scrapService.js
  src/service/userService.js
  src/socket.js
Labels: 🛠 리팩터링, 🧐 동근

#149 [FEAT] 번개 참여 여부 조회 기능 구현
  src/constants/responseMessage.js
  src/controller/lightController.js
  src/db/lightUserDao.js
  src/lib/util.js
  src/routes/lightApi.js
  src/service/lightService.js
Labels: ⚡️ 기능, light, 🐱제준

#152 [FEAT] 번개 찜 여부 조회 기능 구현
  src/constants/responseMessage.js
  src/controller/scrapController.js
  src/db/scrapDao.js
  src/routes/scrapApi.js
  src/service/scrapService.js
Labels: ⚡️ 기능, light, 🐱제준

#153 [release] 기능 추가 업데이트
  src/app.js
  src/constants/responseMessage.js
  src/controller/authController.js
  src/controller/crewController.js
  src/controller/lightController.js
  src/controller/messageController.js
  src/controller/scrapController.js
  src/controller/userController.js
  src/db/authDao.js
  src/db/crewDao.js
  src/db/crewUserDao.js
  src/db/lightDao.js
  src/db/lightUserDao.js
  src/db/messageDao.js
  src/db/scrapDao.js
  src/db/userDao.js
  src/index.js
  src/lib/redis.js
  src/lib/util.js
  src/package-lock.json
  src/package.json
  src/routes/lightApi.js
  src/routes/scrapApi.js
  src/service/authService.js
  src/service/crewService.js
  src/service/lightService.js
  src/service/messageService.js
  src/service/scrapService.js
  src/service/userService.js
  src/socket.js
Labels: 🚀 릴리즈

#155 [FEAT] 번개 소유자인지 확인하는 로직 구현
  src/db/lightDao.js
  src/service/lightService.js
Labels: ⚡️ 기능, light, 🐱제준

#156 [release] 메인 머지
  src/db/lightDao.js
  src/service/lightService.js
Labels: 🚀 릴리즈

#158 [FIX] 번개 조회 시 crewId 별로 조회
  src/controller/lightController.js
  src/db/lightDao.js
  src/routes/lightApi.js
  src/service/lightService.js
Labels: 🐞 버그, light, 🐱제준

#161 [릴리즈] 메인머지
  src/constants/responseMessage.js
  src/controller/authController.js
  src/controller/lightController.js
  src/db/authDao.js
  src/db/lightDao.js
  src/db/userDao.js
  src/package-lock.json
  src/package.json
  src/passport/googleStrategy.js
  src/passport/kakaoStrategy.js
  src/routes/authApi.js
  src/routes/lightApi.js
  src/service/authService.js
  src/service/lightService.js
Labels: 🚀 릴리즈

#162 [릴리즈] fix: 번개 상세 조회 - REST API 형식에 맞게 변경
  src/routes/lightApi.js
Labels: 🚀 릴리즈

#164 [feat] 소켓 서버 구현
  src/middlewares/jwtAuthorization.js
  src/socket.js
Labels: ⚡️ 기능, message

#165 [release] 소켓 통신 릴리즈
  README.md
  REAMDE.md
  src/middlewares/jwtAuthorization.js
  src/socket.js
Labels: 🚀 릴리즈

#167 feat: 슬랙봇 에러 모니터링 추가
  src/app.js
  src/config/index.js
  src/index.js
  src/lib/slack.js
Labels: ⚡️ 기능

#168 [release] 슬랙 모니터링 웹훅 추가
  src/app.js
  src/config/index.js
  src/index.js
  src/lib/slack.js
Labels: 🚀 릴리즈

#169 [FIX] 동아리 수정 기능 추가 및 동아리 개수 제한 삭제
  src/constants/responseMessage.js
  src/controller/crewController.js
  src/db/crewDao.js
  src/routes/crewAPI.js
  src/service/crewService.js
Labels: 🐞 버그, ⚡️ 기능, 🐱제준, crew

#170 [릴리즈] 메인머지
  src/constants/responseMessage.js
  src/controller/crewController.js
  src/db/crewDao.js
  src/routes/crewAPI.js
  src/service/crewService.js
Labels: 🐱제준, 🚀 릴리즈

#172 Feat: 유저 회원가입 API 추가
  src/constants/responseMessage.js
  src/controller/userController.js
  src/db/userDao.js
  src/routes/userAPi.js
  src/service/authService.js
  src/service/userService.js
Labels: ⚡️ 기능, user, 👾승헌

#175 [릴리즈] 메인 머지
  src/constants/responseMessage.js
  src/controller/userController.js
  src/db/lightDao.js
  src/db/userDao.js
  src/routes/userAPi.js
  src/service/authService.js
  src/service/userService.js
Labels: 🚀 릴리즈

#176 Update: 엑세스 토큰 재발급 로직 업데이트
  src/controller/authController.js
  src/db/authDao.js
  src/db/userDao.js
  src/lib/jwtUtil.js
  src/middlewares/jwtAuthorization.js
  src/routes/authApi.js
  src/service/authService.js
Labels: 🛠 리팩터링, user, 👾승헌

#178 Feat: 유저 멀티프로필 상세조회 API 구현
  src/controller/userController.js
  src/db/userDao.js
  src/routes/index.js
  src/routes/userAPi.js
  src/service/userService.js
Labels: ⚡️ 기능, user, 👾승헌

#180 Update: 동아리 권한 표시 필드 추가
  src/db/crewUserDao.js
  src/service/crewService.js
Labels: 🛠 리팩터링, crew, 👾승헌

#182 [feat] 동아리 참여시 동아리 id값 반환
  src/app.js
  src/index.js
  src/passport/googleStrategy.js
  src/passport/kakaoStrategy.js
  src/service/crewService.js
Labels: 🧐 동근, crew

#183 [release] 기능 추가, 버그 수정 릴리즈
  src/app.js
  src/controller/authController.js
  src/controller/userController.js
  src/db/authDao.js
  src/db/crewUserDao.js
  src/db/userDao.js
  src/index.js
  src/lib/jwtUtil.js
  src/middlewares/jwtAuthorization.js
  src/passport/googleStrategy.js
  src/passport/kakaoStrategy.js
  src/routes/authApi.js
  src/routes/index.js
  src/routes/userAPi.js
  src/service/authService.js
  src/service/crewService.js
  src/service/lightService.js
  src/service/userService.js
Labels: 🚀 릴리즈

#184 [hotfix] router 파일명 통일
  src/routes/index.js
Labels: 🚀 릴리즈

#185 [릴리즈] 메인 머지
  src/controller/lightController.js
  src/db/lightDao.js
  src/routes/lightApi.js
  src/service/lightService.js
Labels: 🚀 릴리즈

#144 Firebase SDK 초기화
  .gitignore
  src/db/authDao.js
  src/db/lightDao.js
  src/firebase.js
  src/package-lock.json
  src/package.json
  src/service/crewService.js
  src/service/lightService.js
  src/service/messageService.js
Labels: ⚡️ 기능, 👾승헌

#186 [릴리즈] 메인머지
  .gitignore
  src/db/authDao.js
  src/db/lightDao.js
  src/firebase.js
  src/package-lock.json
  src/package.json
  src/service/crewService.js
  src/service/lightService.js
  src/service/messageService.js
Labels: 🐱제준, 🚀 릴리즈

#187 Fix: db 컬럼명 수정정
  src/db/userDao.js
Labels: 🛠 리팩터링, user, 👾승헌

#188 [릴리즈] 메인머지
  src/controller/lightController.js
  src/db/lightDao.js
  src/routes/lightApi.js
  src/service/lightService.js
Labels: 🚀 릴리즈

#189 [릴리즈] 메인머지
  src/controller/lightController.js
Labels: 🚀 릴리즈

#190 [릴리즈] 메인 머지
  src/middlewares/multer.js
  src/routes/lightApi.js
Labels: 🚀 릴리즈

#191 [릴리즈] 메인 머지
  src/routes/lightApi.js
Labels: 🚀 릴리즈
